### ISSUE TITLE
opt_visc: 8 leads to io_fesom_file.F90 can not find dimension with size           0

### ISSUE THREAD

**Issue by JanStreffing** [FESOM/fesom2#626]
I've been trying to get TCO319-BOLD running for Nils Hutter and GEOMAR. 

I am faced with the following error:
```
1795:  error in line          525 io_fesom_file.F90 can not find dimension with size           0
2177:  error in line          525 io_fesom_file.F90 can not find dimension with size           0
 385:  error in line          525 io_fesom_file.F90 can not find dimension with size           0
```
The line in question: 
https://github.com/FESOM/fesom2/blob/2c049ce5335c368f67249216cbb3dcca236f2241/src/io_fesom_file.F90#L515-L527

Anyone got an idea what's causing this?

**Comment by JanStreffing** [comment]
I found I can activate/deactivate this error by turning on / off dynamic backscatter:
```
    add_namelist_changes:
        namelist.dyn:
            dynamics_visc:
                opt_visc: 8
```
Default `opt_visc: 7`

@StJuricke
